import Head from 'next/head' 
import React from 'react'

export const Seo = ({title}: {title: string}) => {
	return (
		<Head>
			<title>{title} | Space Tourism</title>
			<meta name="description" content="Generated by create next app" />
		</Head>
	)
}
